import Head from "next/head";
import { SignIn, SignOutButton, useUser, SignInButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Sorry... We have no posts yet</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full h-full md:max-w-2xl border-x border-slate-400" >
          <div className="border-b border-slate-400 p-4 flex justify-center" >
            { user? <SignOutButton/> : <SignInButton/> }
          </div>
          <div className="flex flex-col" >
            {data?.map((post) => (
              <div className="border-b border-slate-400 p-8" key={post.id}>{post.content}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
